### ISSUE TITLE
Read success, but no data publishing to MQTT

### ISSUE THREAD

**Issue by bassicrob** [bvlaicu/home-assistant-addons#13]
I have installed on HA as an Add-On, by adding the repository to the HA Add-Ons page.  I am running Supervised - core-2021.1.5 on Ubuntu 18.04.5 LTS (I know planning a migration to Proxmox in the very near future) on an Dell i5.

I am able to see that I get a reading in the logs, and I see a connection in MQTT logs from oru_meter_reader. I have password authentication via accesscontrollist defined and it appears to log-in successfully, but nothing is published to MQTT electric_meter/# or . 

My ORU log from the read on the meter onwards throws a bunch of exceptions:
```
message: {'startTime': '2021-08-29T23:00:00-04:00', 'endTime': '2021-08-29T23:15:00-04:00', 'value': 0.987, 'uom': 'KWH'}
Task exception was never retrieved
future: <Task finished coro=<Meter.browse() done, defined at /usr/local/lib/python3.7/dist-packages/coned/meter.py:116> exception=NetworkError('Protocol error Page.navigate: Target closed.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 162, in browse
    await api_page.goto(api_url)
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/page.py", line 877, in goto
    result = await self._navigate(url, referrer)
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/page.py", line 892, in _navigate
    'Page.navigate', {'url': url, 'referrer': referrer})
pyppeteer.errors.NetworkError: Protocol error Page.navigate: Target closed.
Task was destroyed but it is pending!
task: <Task pending coro=<NavigatorWatcher._createTimeoutPromise.<locals>._timeout_func() done, defined at /usr/local/lib/python3.7/dist-packages/pyppeteer/navigator_watcher.py:95> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6d5a1ec978>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<wait() done, defined at /usr/lib/python3.7/asyncio/tasks.py:335> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6d5a1ecc18>()]> cb=[NavigatorWatcher.__init__.<locals>.<lambda>() at /usr/local/lib/python3.7/dist-packages/pyppeteer/navigator_watcher.py:54]>
```
Messages at initialization show a few errors as well before the `CONSOLE` messages:
```
2021-08-30T04:09:04.488819000Z Starting endless loop..
2021-08-30T04:09:04.956481000Z [0830/000904.956093:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2021-08-30T04:09:04.962837000Z DevTools listening on ws://127.0.0.1:58793/devtools/browser/0445bc6c-cb44-4425-83d8-0089747c91bc
2021-08-30T04:09:04.968780000Z [0830/000904.965104:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
2021-08-30T04:09:05.219627000Z [0830/000905.219465:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2021-08-30T04:09:05.219980000Z DevTools listening on ws://127.0.0.1:37625/devtools/browser/a42a099f-635c-4cb0-88c9-cf52dd6ce5b0
2021-08-30T04:09:05.226900000Z [0830/000905.223464:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
```
Log from MQTT showing successful connect:
```
1630294497: New connection from 172.30.32.1 on port 1883.
[INFO] found electricmeter on local database
1630294498: New client connected from 172.30.32.1 as oru_meter_reader (p2, c1, k60, u'electricmeter').
1630294498: Client oru_meter_reader disconnected.
```

**Comment by HiTechTLS** [comment]
Using HA.OS, and install of "Orange and Rockland Utility to MQTT Bridge" using addon repo in same way as you. Seeing very intermittent reads, but nothing in MQTT

The good

message: {'startTime': '2022-02-06T17:45:00-05:00', 'endTime': '2022-02-06T18:00:00-05:00', 'value': 0.225, 'uom': 'KWH'}

The bad

[0206/201020.174838:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

Traceback (most recent call last):
  File "run.py", line 26, in <module>
    mqttc.connect(os.getenv("MQTT_HOST"))
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by bassicrob** [comment]
No offense to the creator, but my solution was installing an ESP-Home device with an IR receiver over the test port.  There is a light that blinks for each 1kwh consumed which the ESP reads and sends to HA and displayed on Energy Dashboard.  So far it has been reliable and within a tolerable accuracy to my actual meter reads. 

Now if ConEd would actually publish their kWh rate changes so that we can parse into HA we'd be better informed of our usage than the surprise they pulled last month which is just making headlines!

**Comment by HiTechTLS** [comment]
Oh man, loving both natural gas and electricity sourced from natural gas right now. ITS THE FUTURE!

**Comment by HiTechTLS** [comment]
The real solution would be to implement this directly

https://cdnc-dcxprod2-sitecore.azureedge.net/-/media/files/coned/documents/accountandbilling/share-my-data/onboarding-doc.pdf?rev=f7529ca6629241b3b720aa48eec60714&hash=0A46AA8381FF10A0A6EE1E506C99F5F7

**Comment by rhdny** [comment]
But unfortunately they don’t allow that direct to consumers and with meter data encrypted, we have to scrape….

**Comment by HiTechTLS** [comment]
> 

But, is the scraping working for you? I have yet to get a single element from Coned into HA. I was hoping more for HA main build to include "Green Button" support for all these energy suppliers, seems like a no brainer.
