### ISSUE TITLE
Python library works, addon does not

### ISSUE THREAD

**Issue by cromulus** [bvlaicu/home-assistant-addons#28]
Hi!
I'm trying to get the homeassistant addon working, and I'm getting an error.

The odd thing is that with the same credentials and information, your [python library](https://github.com/bvlaicu/coned) connects and returns values just fine.

This is the error:
```[1108/104126.331539:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:40463/devtools/browser/e8214e6a-f63f-4fa4-a92b-f343c9eeebd9
[1108/104126.335429:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
[1108/104126.543419:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:45659/devtools/browser/6ce91c69-0fa3-426c-ae89-6ab4cb7004c1
[1108/104126.553603:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
[1108/104145.670691:INFO:CONSOLE(2)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: https://acdn-prod-bsdce-ngcx-va.azureedge.net/va/coned-va-build.min.js (2)
[1108/104148.832926:INFO:CONSOLE(2)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: https://acdn-prod-bsdce-ngcx-va.azureedge.net/va/coned-va-build.min.js (2)
Task exception was never retrieved
future: <Task finished coro=<Meter.browse() done, defined at /usr/local/lib/python3.7/dist-packages/coned/meter.py:131> exception=NameError("name 'raw_data' is not defined")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 225, in browse
    self._LOGGER.debug(f"raw_data = {raw_data}")
NameError: name 'raw_data' is not defined
Creating Meter
Calling meter.last_read()..
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 96, in all_reads
    await self.browse()
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 225, in browse
    self._LOGGER.debug(f"raw_data = {raw_data}")
NameError: name 'raw_data' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    startTime, endTime, value, uom = asyncio.get_event_loop().run_until_complete(meter.last_read())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 127, in last_read
    all_available_reads = await self.all_reads()
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 123, in all_reads
    raise MeterError("Error requesting meter data")
coned.meter.MeterError: Error requesting meter data```

additionally, attempting to edit configuration.yaml, I get this error when i check it:
```Integration error: customize_glob - Integration 'customize_glob' not found.```

Thank you for all your work on this! Really appreciate it!

**Comment by jgoulah** [comment]
same issue

**Comment by nebriv** [comment]
Same issue here as well

**Comment by jgoulah** [comment]
I just posted a fix with explanation. Hopefully it will be merged.

**Comment by Henchman-21** [comment]
Has 1.0.3 resolved this for you?  I'm just installing this for the first time in the last few days so I may have another issue, just saw this thread and I think I'm getting the same error around raw_data when trying to connect (with or w/o account #).

```
Sleeping 5 mins..
[1222/053303.277803:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:39189/devtools/browser/8ad4b636-00aa-47d6-9571-3caf052d7d7c
[1222/053304.133453:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:57741/devtools/browser/9dc324b6-a48f-4c81-88b8-d611ee3b255a
[1222/053333.493776:INFO:CONSOLE(2)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: https://acdn-prod-bsdce-ngcx-va.azureedge.net/va/coned-va-build.min.js (2)
[1222/053335.967460:INFO:CONSOLE(2)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: https://acdn-prod-bsdce-ngcx-va.azureedge.net/va/coned-va-build.min.js (2)
[1222/053336.507952:INFO:CONSOLE(2)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: https://acdn-prod-bsdce-ngcx-va.azureedge.net/va/coned-va-build.min.js (2)
Task exception was never retrieved
future: <Task finished coro=<Meter.browse() done, defined at /usr/local/lib/python3.7/dist-packages/coned/meter.py:131> exception=NameError("name 'raw_data' is not defined")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 225, in browse
    self._LOGGER.debug(f"raw_data = {raw_data}")
NameError: name 'raw_data' is not defined
Creating Meter
Calling meter.last_read()..
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 96, in all_reads
    await self.browse()
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 225, in browse
    self._LOGGER.debug(f"raw_data = {raw_data}")
NameError: name 'raw_data' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    startTime, endTime, value, uom = asyncio.get_event_loop().run_until_complete(meter.last_read())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 127, in last_read
    all_available_reads = await self.all_reads()
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 123, in all_reads
    raise MeterError("Error requesting meter data")
coned.meter.MeterError: Error requesting meter data
Sleeping 5 mins..
```

**Comment by nebriv** [comment]
1.0.3 resolved the issue for me - still having trouble getting HA to
understand the data but thats just my own inexperience with HA :)

Make sure you remove your account number from the config.

**Comment by Henchman-21** [comment]
So I've removed the acct # and getting a different error now (should I start a new thread?) Looks like a resolution error but I know HA can resolve out and reach other services both internal and external.

```
Starting endless loop..
[1222/113128.255893:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:50639/devtools/browser/6edc4a3b-7b7d-477f-a1e3-145eed61ad1d
[1222/113129.118189:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:51453/devtools/browser/33b390e6-849f-44b5-b42e-9646adea949c
Task exception was never retrieved
future: <Task finished coro=<Meter.browse() done, defined at /usr/local/lib/python3.7/dist-packages/coned/meter.py:131> exception=TimeoutError('Navigation Timeout Exceeded: 10000 ms exceeded.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 154, in browse
    await page.goto('https://www.' + self.site + '.com/en/login', {'waitUntil': 'domcontentloaded', 'timeout': 10000})
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/page.py", line 837, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 10000 ms exceeded.
[1222/113156.474461:INFO:CONSOLE(2)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: https://acdn-prod-bsdce-ngcx-va.azureedge.net/va/coned-va-build.min.js (2)
[1222/113158.827665:INFO:CONSOLE(2)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: https://acdn-prod-bsdce-ngcx-va.azureedge.net/va/coned-va-build.min.js (2)
[1222/113203.705651:INFO:CONSOLE(1)] "::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.", source: https://nextweb-static.opower.com/maestro/themes/maestro-theme-cned/b2e59ead212ab1b9c48f37099a33914a/pages/apps/maestro-widget-library-core/index.generated.embedded-api.33.min.js (1)
[1222/113207.533511:INFO:CONSOLE(2)] "Infinity Analytics was unable to load.", source: https://nextweb-static.opower.com/maestro/themes/maestro-theme-cned/b2e59ead212ab1b9c48f37099a33914a/pages/apps/maestro-widget-library-core/index.generated.embedded-api.app.min.js (2)
Task exception was never retrieved
future: <Task finished coro=<resp() done, defined at /usr/local/lib/python3.7/dist-packages/coned/meter.py:236> exception=NetworkError('Protocol error (Network.getResponseBody): No resource with given identifier found')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 242, in resp
    raw_data = await res.text()
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/network_manager.py", line 669, in text
    content = await self.buffer()
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/network_manager.py", line 654, in _bufread
    'requestId': self._request._requestId
pyppeteer.errors.NetworkError: Protocol error (Network.getResponseBody): No resource with given identifier found
Creating Meter
Calling meter.last_read()..
  res.url: https://cned.opower.com/ei/edge/apis/cws-real-time-ami-v1/cws/cned/accounts/92a29302-a5ff-11ec-91ee-02001700dbdb/meters/5248924/usage
  res.status: 200
  res.url: https://cned.opower.com/ei/edge/apis/cws-real-time-ami-v1/cws/cned/accounts/92a29302-a5ff-11ec-91ee-02001700dbdb/meters/5248924/usage
  res.status: 200
message: {'startTime': '2022-12-22T10:00:00-05:00', 'endTime': '2022-12-22T10:15:00-05:00', 'value': 0.051, 'uom': 'KWH', 'asOf': '2022-12-22T11:32:37.887413'}
Connecting to mqtt hassio.local as coned
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    mqttc.connect(mqtthost)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
Sleeping 5 mins..

```

**Comment by nebriv** [comment]
Yeah that looks like it connected to coned and got the data fine. Looks
like an issue connecting the mqtt server maybe?

**Comment by Henchman-21** [comment]
Gotcha, yeah I'll chase that.  Thanks!

**Comment by jgoulah** [comment]
this can be closed
